try:
    k = int("budet_error")
except ValueError:
    pass
finally:
    print("Дошел до finally")
